/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Themes */
        get: operations["list_themes_themes_get"];
        put?: never;
        /** Create Theme */
        post: operations["create_theme_themes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Theme */
        get: operations["get_theme_themes__name__get"];
        /** Update Theme */
        put: operations["update_theme_themes__name__put"];
        post?: never;
        /** Delete Theme */
        delete: operations["delete_theme_themes__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{name}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename Theme */
        put: operations["rename_theme_themes__name__rename_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Channels */
        get: operations["channels_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Theme */
            theme: string;
            /** @default monthly */
            frequency: components["schemas"]["Frequency"];
            /** @default binary */
            count_mode: components["schemas"]["CountMode"];
            /** Date Start */
            date_start?: string | null;
            /** Date End */
            date_end?: string | null;
            /** Channels */
            channels?: string[] | null;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            kpi: components["schemas"]["KpiResponse"];
            /** Series */
            series: components["schemas"]["TimeSeriesPoint"][];
            /** Top Channels */
            top_channels: components["schemas"]["TopChannel"][];
            /** Descriptive */
            descriptive: components["schemas"]["DescriptiveRow"][];
            /** Preview Titles */
            preview_titles: components["schemas"]["PreviewTitle"][];
            request: components["schemas"]["AnalysisRequest"];
        };
        /** ChannelCoverage */
        ChannelCoverage: {
            /** Channel */
            channel: string;
            /**
             * Date Min
             * Format: date
             */
            date_min: string;
            /**
             * Date Max
             * Format: date
             */
            date_max: string;
            /** N Obs */
            n_obs: number;
            /** Share Pct */
            share_pct: number;
        };
        /**
         * CountMode
         * @enum {string}
         */
        CountMode: "binary" | "intensity";
        /** DecadePoint */
        DecadePoint: {
            /** Channel */
            channel: string;
            /** Decade */
            decade: number;
            /** Decade Label */
            decade_label: string;
            /** N */
            n: number;
            /** Pct */
            pct: number;
        };
        /** DescriptiveRow */
        DescriptiveRow: {
            /** Indicateur */
            indicateur: string;
            /** Valeur */
            valeur: unknown;
        };
        /**
         * Frequency
         * @enum {string}
         */
        Frequency: "monthly" | "quarterly" | "yearly";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Data Loaded */
            data_loaded: boolean;
            /** N Rows */
            n_rows: number;
            /**
             * Source
             * @enum {string}
             */
            source: "local" | "hf" | "unknown";
            /** Issues */
            issues?: string[];
        };
        /** KpiResponse */
        KpiResponse: {
            /** N Total */
            n_total: number;
            /** N Matched */
            n_matched: number;
            /** Occ Concept Total */
            occ_concept_total: number;
            /** Freq Mean */
            freq_mean: number;
            /** Net Signal Total */
            net_signal_total: number;
            /** Up Total */
            up_total: number;
            /** Down Total */
            down_total: number;
            /** Ambiguous Total */
            ambiguous_total: number;
        };
        /** MetadataResponse */
        MetadataResponse: {
            /** N Total */
            n_total: number;
            /** Date Min */
            date_min: string | null;
            /** Date Max */
            date_max: string | null;
            /** Channels */
            channels: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "local" | "hf" | "unknown";
        };
        /** PreviewTitle */
        PreviewTitle: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Channel */
            channel?: string | null;
            /** Title */
            title: string;
            /** Occ Concept */
            occ_concept: number;
            /** Occ Up */
            occ_up: number;
            /** Occ Down */
            occ_down: number;
            /** Direction */
            direction: number;
            /**
             * Direction Label
             * @enum {string}
             */
            direction_label: "flat" | "up" | "down" | "ambiguous";
            /** Source File */
            source_file?: string | null;
        };
        /** ThemeCreateRequest */
        ThemeCreateRequest: {
            /** Name */
            name: string;
            /** Concept */
            concept?: string[];
            /** Up */
            up?: string[];
            /** Down */
            down?: string[];
        };
        /** ThemeDictionary */
        ThemeDictionary: {
            /** Name */
            name: string;
            /** Concept */
            concept?: string[];
            /** Context */
            context?: string[];
            /** Up */
            up?: string[];
            /** Down */
            down?: string[];
        };
        /** ThemeRenameRequest */
        ThemeRenameRequest: {
            /** New Name */
            new_name: string;
        };
        /** ThemeSummary */
        ThemeSummary: {
            /** Name */
            name: string;
            /** N Concept */
            n_concept: number;
            /** N Up */
            n_up: number;
            /** N Down */
            n_down: number;
        };
        /** ThemeUpdateRequest */
        ThemeUpdateRequest: {
            /** Concept */
            concept?: string[] | null;
            /** Up */
            up?: string[] | null;
            /** Down */
            down?: string[] | null;
        };
        /** TimeSeriesPoint */
        TimeSeriesPoint: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Total Titles */
            total_titles: number;
            /** Matched Titles */
            matched_titles: number;
            /** Occurrences Concept */
            occurrences_concept: number;
            /** Frequency */
            frequency: number;
            /** Up Titles */
            up_titles: number;
            /** Down Titles */
            down_titles: number;
            /** Ambiguous Titles */
            ambiguous_titles: number;
            /** Net Signal */
            net_signal: number;
        };
        /** TopChannel */
        TopChannel: {
            /** Channel */
            channel: string;
            /** Total Titles */
            total_titles: number;
            /** Matched Titles */
            matched_titles: number;
            /** Frequency */
            frequency: number;
            /** Up Titles */
            up_titles: number;
            /** Down Titles */
            down_titles: number;
            /** Ambiguous Titles */
            ambiguous_titles: number;
            /** Net Signal */
            net_signal: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metadata_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
        };
    };
    list_themes_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeSummary"][];
                };
            };
        };
    };
    create_theme_themes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDictionary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_theme_themes__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDictionary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_theme_themes__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDictionary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_theme_themes__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_theme_themes__name__rename_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeDictionary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    channels_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelCoverage"][];
                };
            };
        };
    };
    coverage_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecadePoint"][];
                };
            };
        };
    };
    analyze_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_export_csv_get: {
        parameters: {
            query: {
                theme: string;
                frequency?: components["schemas"]["Frequency"];
                date_start?: string | null;
                date_end?: string | null;
                channels?: string[] | null;
                separator?: string;
                decimal?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
